on: '2'
services:
   db:
     image: postgres:9.5
   web:
     image: abhivision/roboadvisor:v13
     command: python3 manage.py runserver 0.0.0.0:8000
     ports:
       - "8000:8000"
     depends_on:
       - db
